package org.example;

public enum TokenType {

    PLUS, MINUS, MULTIPLY, DIVIDE, ASSIGN, COMMA,
    LEFT_PARENTHESES, RIGHT_PARENTHESES, LEFT_BRACES, RIGHT_BRACES,
    EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,

    IDENTIFIER, NUMBER, FUN,

    IF, THEN, ELSE, RETURN, DO, WHILE, TRUE, FALSE,
    EOF

}